import fs from "node:fs";
import { LEGAL_ENUMS, EntityType, EdgeType, legalEdge } from "../../src/lib/legal/schema.ts";
import { ID_PATTERNS, ID_AUTHORITIES, NATIVE_NUMERIC_TYPES, NATIVE_NUMERIC_AUTHORITIES } from "../../src/lib/legal/identity.ts";
const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
let sql = `-- Generated by scripts/legal/generate-db.ts from the shared vocabulary and endpoint validator.\n-- Private additive round 3 contract. No existing collection is released or modified.\ncreate schema if not exists legal_atlas;\nrevoke all on schema legal_atlas from public, anon, authenticated;\n`;
for (const [name, labels] of Object.entries(LEGAL_ENUMS)) {
  if (typeof labels === "string") continue;
  sql += `create type legal_atlas.${name} as enum (${Object.keys(labels).map(quote).join(",")});\n`;
}
sql += `create table legal_atlas.edge_contract (kind legal_atlas.edge_type not null, from_type legal_atlas.entity_type not null, to_type legal_atlas.entity_type not null, primary key(kind,from_type,to_type));\ninsert into legal_atlas.edge_contract values\n`;
const combinations: string[] = [];
for (const kind of EdgeType.options) for (const from of EntityType.options) for (const to of EntityType.options) {
  const ref = (type: string, id: string) => ({ type, id, id_authority: "publisher", version: "source-version" });
  if (legalEdge.safeParse({ type: kind, from: ref(from, "a"), to: ref(to, "b"), source_record: ref("source_doc", "c"), source_url: "https://example.org/source", date: "2000-01-01", extraction_method: "regex", confidence: 1, evidence: { paragraph_id: "1" }, review_status: "approved", treatment: null, role: null }).success) combinations.push(`(${quote(kind)},${quote(from)},${quote(to)})`);
}
sql += combinations.join(",\n") + ";\n";
const rules = [
  ...Object.entries(ID_PATTERNS).map(([type, pattern]) => `if p->>'type'=${quote(type)} and p->>'id' !~ ${quote(pattern)} then errors:=array_append(errors,'id:canonical_format'); end if;`),
  ...Object.entries(ID_AUTHORITIES).map(([type, authorities]) => `if p->>'type'=${quote(type)} and p->>'id_authority' not in (${authorities.map(quote).join(',')}) then errors:=array_append(errors,'id_authority:publisher'); end if;`),
  `if p->>'type' in (${NATIVE_NUMERIC_TYPES.map(quote).join(',')}) and p->>'id_authority' in (${NATIVE_NUMERIC_AUTHORITIES.map(quote).join(',')}) and p->>'id' !~ '^[1-9][0-9]*$' then errors:=array_append(errors,'id:native_numeric'); end if;`,
].join('\n  ');
sql += fs.readFileSync("database/contracts/legal-atlas-v3.body.sql", "utf8").replace('-- GENERATED_RECORD_ID_RULES', () => rules);
const destination = "database/contracts/legal-atlas-v3.generated.sql";
if (process.argv.includes("--check")) {
  if (!fs.existsSync(destination) || fs.readFileSync(destination, "utf8") !== sql) throw new Error("Generated database enum/edge contract differs from shared schema");
} else fs.writeFileSync(destination, sql);
console.log(JSON.stringify({ generated: destination, entity_types: EntityType.options.length, relationship_pairs: combinations.length }));
