expected(dataset,id,category,state,title,source_url,ordinal,item,detail,text,filters,county_geoids) as (
 select 'ecfr_hierarchy',n.id,'ecfr_hierarchy',null::text,n.data->>'heading',n.provenance->>'source_url',n.ordinal,
 jsonb_build_object('id',n.id,'title',n.data->>'heading','subtitle','Title '||(n.data->>'title_number')||' · '||(n.data->>'node_type'),
 'cells',jsonb_build_object('title_number',n.data->>'title_number','node_type',n.data->>'node_type','node_identifier',n.data->>'node_identifier','reserved',n.data->'reserved','snapshot_as_of',n.data->>'snapshot_as_of'),
 'links',jsonb_build_array(jsonb_build_object('url',n.provenance->>'source_url','label','Dated publisher hierarchy')),'badges',jsonb_build_array(n.data->>'node_type',case when n.data->>'reserved'='true' then 'Reserved' else 'Publisher heading' end)),
 jsonb_build_object('id',n.id,'title',n.data->>'heading','subtitle','Title '||(n.data->>'title_number')||' · '||(n.data->>'node_type'),
 'facts',jsonb_build_array(jsonb_build_array('CFR title',n.data->>'title_number'),jsonb_build_array('Node type',n.data->>'node_type'),jsonb_build_array('Native identifier',n.data->>'node_identifier'),jsonb_build_array('Reserved',n.data->'reserved'),jsonb_build_array('Dated snapshot',n.data->>'snapshot_as_of'),jsonb_build_array('Native publisher path',n.native_id),jsonb_build_array('Child node associations',jsonb_array_length(n.data->'child_native_ids'))),
 'links',jsonb_build_array(jsonb_build_object('url',n.provenance->>'source_url','label','Dated publisher hierarchy'))||case when n.data->>'parent_native_id' is not null then jsonb_build_array(jsonb_build_object('url',__PARENT_TOKEN__,'label','Parent heading')) else '[]'::jsonb end,
 'sections',jsonb_build_array(jsonb_build_object('title','Child headings','items',coalesce(ci.items,'[]'::jsonb))),
 'qualification',__HIERARCHY_QUALIFICATION__,'provenance',jsonb_build_object('source_system','ecfr','schema_version',n.schema_version,'source_as_of',n.source_as_of,'retrieved_at',n.retrieved_at,'source_url',n.provenance->>'source_url','original_sha256',n.provenance->>'source_sha256','record_sha256',n.payload_sha256,'native_publisher_metadata',n.data->'source_node','unidentified_heading_metadata',n.data->'unidentified_headings')),
 jsonb_pretty(n.data),jsonb_build_object('_listing','true','native_id',n.native_id,'title_number',n.data->>'title_number','node_type',n.data->>'node_type','reserved',n.data->>'reserved','snapshot_as_of',n.data->>'snapshot_as_of'),'{}'::text[] from nodes n left join child_items ci on ci.parent_id=n.native_id
 union all
 select 'ecfr_authority_notes',n.id,'ecfr_authority_notes',null::text,n.data->>'heading',n.provenance->>'source_url',n.ordinal,
 jsonb_build_object('id',n.id,'title',n.data->>'heading','subtitle','Snapshot '||(n.data->>'snapshot_as_of'),'cells',jsonb_build_object('title_number',n.data->>'title_number','part_number',n.data->>'part_number','snapshot_as_of',n.data->>'snapshot_as_of','historical_scope',n.data->'historical_scope'),'links',jsonb_build_array(jsonb_build_object('url',n.provenance->>'source_url','label','Dated XML authority/source evidence'))),
 jsonb_build_object('id',n.id,'title',n.data->>'heading','subtitle','Snapshot '||(n.data->>'snapshot_as_of'),'facts',jsonb_build_array(jsonb_build_array('CFR title',n.data->>'title_number'),jsonb_build_array('Part',n.data->>'part_number'),jsonb_build_array('Snapshot',n.data->>'snapshot_as_of'),jsonb_build_array('Historical research snapshot',n.data->'historical_scope'),jsonb_build_array('Authority note',n.data->>'authority_note'),jsonb_build_array('Source note',n.data->>'source_note'),jsonb_build_array('XML section headings',jsonb_array_length(n.data->'sections'))),'links',jsonb_build_array(jsonb_build_object('url',n.provenance->>'source_url','label','Dated XML authority/source evidence')),'section_source_notes',n.data->'sections','qualification',__NOTES_QUALIFICATION__,'provenance',jsonb_build_object('source_system','ecfr','schema_version',n.schema_version,'source_as_of',n.source_as_of,'retrieved_at',n.retrieved_at,'original_sha256',n.provenance->>'source_sha256','record_sha256',n.payload_sha256)),
 jsonb_pretty(n.data),jsonb_build_object('_listing','true','native_id',n.native_id,'title_number',n.data->>'title_number','part_number',n.data->>'part_number','snapshot_as_of',n.data->>'snapshot_as_of','historical_scope',n.data->>'historical_scope'),'{}'::text[] from notes n
)
