with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'parent_court_id','courts',e.data->>'parent_court_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='courts' and t.native_id=e.data->>'parent_court_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='courts' and nullif(e.data->>'parent_court_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'court_id','courts',e.data->>'court_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='courts' and t.native_id=e.data->>'court_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='courthouses' and nullif(e.data->>'court_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'from_court_id','courts',e.data->>'from_court_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='courts' and t.native_id=e.data->>'from_court_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='court-appeals-to' and nullif(e.data->>'from_court_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'to_court_id','courts',e.data->>'to_court_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='courts' and t.native_id=e.data->>'to_court_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='court-appeals-to' and nullif(e.data->>'to_court_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'person_id','people',e.data->>'person_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='people' and t.native_id=e.data->>'person_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='positions' and nullif(e.data->>'person_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'court_id','courts',e.data->>'court_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='courts' and t.native_id=e.data->>'court_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='positions' and nullif(e.data->>'court_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'school_id','schools',e.data->>'school_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='schools' and t.native_id=e.data->>'school_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='positions' and nullif(e.data->>'school_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'appointer_id','positions',e.data->>'appointer_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='positions' and t.native_id=e.data->>'appointer_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='positions' and nullif(e.data->>'appointer_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'predecessor_id','people',e.data->>'predecessor_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='people' and t.native_id=e.data->>'predecessor_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='positions' and nullif(e.data->>'predecessor_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'supervisor_id','people',e.data->>'supervisor_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='people' and t.native_id=e.data->>'supervisor_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='positions' and nullif(e.data->>'supervisor_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'person_id','people',e.data->>'person_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='people' and t.native_id=e.data->>'person_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='educations' and nullif(e.data->>'person_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'school_id','schools',e.data->>'school_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='schools' and t.native_id=e.data->>'school_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='educations' and nullif(e.data->>'school_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'person_id','people',e.data->>'person_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='people' and t.native_id=e.data->>'person_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='political-affiliations' and nullif(e.data->>'person_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'person_id','people',e.data->>'person_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='people' and t.native_id=e.data->>'person_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='races' and nullif(e.data->>'person_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'race_id','race-choices',e.data->>'race_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='race-choices' and t.native_id=e.data->>'race_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='races' and nullif(e.data->>'race_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'is_alias_of_id','people',e.data->>'is_alias_of_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='people' and t.native_id=e.data->>'is_alias_of_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='people' and nullif(e.data->>'is_alias_of_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'is_alias_of_id','schools',e.data->>'is_alias_of_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='schools' and t.native_id=e.data->>'is_alias_of_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='schools' and nullif(e.data->>'is_alias_of_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;

with written as (insert into corpus_ingest.relationships(source_system,from_type,from_id,field,to_type,to_id,evidence_sha256,inferred,target_present,run_id) select e.source_system,e.entity_type,e.native_id,'position_id','positions',e.data->>'position_id',e.payload_sha256,lower(coalesce(e.data->>'has_inferred_values','false'))=any(array['true','t','1']),exists(select 1 from corpus_ingest.entities t where t.source_system=e.source_system and t.entity_type='positions' and t.native_id=e.data->>'position_id' and t.review_status<>'quarantined'),'494cfa52-74c5-42ac-a770-80e46b9a3035'::uuid from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='retention-events' and nullif(e.data->>'position_id','') is not null on conflict do nothing returning 1) select count(*) inserted from written;