-- CourtListener public reference projection, courtlistener-reference-view/1.
-- Stage 1 only: preserve reversible testing-court decisions and register seven new
-- reference datasets. No rows are bulk-projected or published by this file.
-- Run one <=2000-row transaction at a time using project-reference-metadata-v1-batch.sql.
-- After each dataset is complete, use project-reference-metadata-v1-publish.sql;
-- its exact count/content/provenance verification gates ready=true.
-- Supabase connector request quotas are shared across workers: pace and honor Retry-After.

with targets as materialized (select e.* from corpus_ingest.entities e where e.source_system='courtlistener' and e.entity_type='courts' and e.data->>'jurisdiction'='T' and e.native_id in ('psc','test')), decisions as (insert into corpus_ingest.cleanup_decisions(dataset,record_id,issue,disposition,reason,evidence,original_record,replacement,run_id) select 'cl_courts','cl:courts:'||t.native_id,'explicit_source_testing_court','quarantine','CourtListener source explicitly classifies this native record with jurisdiction T (testing/training); exclude from the public court reference projection while preserving native payload, versions and retrieval provenance.',jsonb_build_object('decision_version','courtlistener-reference-quarantine/1','native_id',t.native_id,'source_jurisdiction',t.data->>'jurisdiction','source_name',t.data->>'full_name','source_in_use',t.data->>'in_use','source_url',t.provenance->>'source_url','source_as_of',t.source_as_of,'payload_sha256',t.payload_sha256,'dependent_reference_count',0,'scope','Only the two native source testing/training court records, not historical or inactive real courts.'),to_jsonb(t),to_jsonb(t)||jsonb_build_object('review_status','quarantined'),t.last_run from targets t on conflict(dataset,record_id,issue) do nothing returning record_id,original_record), changed as (update corpus_ingest.entities e set review_status='quarantined' from targets t where e.source_system=t.source_system and e.entity_type=t.entity_type and e.native_id=t.native_id and e.payload_sha256=t.payload_sha256 and (exists(select 1 from decisions d where d.record_id='cl:courts:'||t.native_id and d.original_record->>'payload_sha256'=t.payload_sha256) or exists(select 1 from corpus_ingest.cleanup_decisions d where d.dataset='cl_courts' and d.record_id='cl:courts:'||t.native_id and d.issue='explicit_source_testing_court' and d.original_record->>'payload_sha256'=t.payload_sha256)) returning e.native_id,e.review_status,e.payload_sha256) select jsonb_build_object('decisions_created',(select count(*) from decisions),'quarantined',(select jsonb_agg(to_jsonb(c)) from changed c)) as receipt;

with specs(entity_type,dataset,label,category,columns) as (values
 ('courts','cl_courts','CourtListener courts — September 2026 snapshot','court_reference', '[{"key":"native_id","label":"Native court ID"},{"key":"jurisdiction","label":"Jurisdiction code"},{"key":"in_use","label":"In use (source)"},{"key":"source_as_of","label":"Snapshot date"}]'::jsonb),
 ('courthouses','cl_courthouses','CourtListener courthouse records — September 2026 snapshot','court_reference','[{"key":"native_id","label":"Native ID"},{"key":"court_id","label":"Court ID"},{"key":"city","label":"City"},{"key":"state","label":"Recorded state"},{"key":"source_as_of","label":"Snapshot date"}]'::jsonb),
 ('court-appeals-to','cl_court_appeals_to','CourtListener recorded appeals-to relationships','court_reference','[{"key":"native_id","label":"Native relationship ID"},{"key":"from_court_id","label":"From court ID"},{"key":"to_court_id","label":"To court ID"},{"key":"source_as_of","label":"Snapshot date"}]'::jsonb),
 ('people','cl_people','CourtListener people and explicit aliases — September 2026 snapshot','historical_biography','[{"key":"native_id","label":"Native person ID"},{"key":"fjc_id","label":"FJC ID (source)"},{"key":"is_alias_of_id","label":"Explicit alias of"},{"key":"source_as_of","label":"Snapshot date"}]'::jsonb),
 ('positions','cl_positions','CourtListener positions and employment records — September 2026 snapshot','judicial_service','[{"key":"native_id","label":"Native position ID"},{"key":"person_id","label":"Person ID"},{"key":"court_id","label":"Court ID"},{"key":"position_type","label":"Position type (source)"},{"key":"date_start","label":"Recorded start"},{"key":"date_termination","label":"Recorded termination"},{"key":"source_as_of","label":"Snapshot date"}]'::jsonb),
 ('educations','cl_educations','CourtListener education records — September 2026 snapshot','biographical_reference','[{"key":"native_id","label":"Native education ID"},{"key":"person_id","label":"Person ID"},{"key":"school_id","label":"School ID"},{"key":"degree_year","label":"Degree year"},{"key":"source_as_of","label":"Snapshot date"}]'::jsonb),
 ('schools','cl_schools','CourtListener schools and explicit aliases — September 2026 snapshot','biographical_reference','[{"key":"native_id","label":"Native school ID"},{"key":"is_alias_of_id","label":"Explicit alias of"},{"key":"source_as_of","label":"Snapshot date"}]'::jsonb)
), totals as (
 select s.*,count(e.*) as n from specs s left join corpus_ingest.entities e
   on e.source_system='courtlistener' and e.entity_type=s.entity_type and e.review_status<>'quarantined' and e.source_as_of=date '2026-09-30' and not exists (select 1 from corpus_ingest.entities qc where qc.source_system=e.source_system and qc.entity_type='courts' and qc.review_status='quarantined' and ((e.entity_type in ('courthouses','positions') and e.data->>'court_id'=qc.native_id) or (e.entity_type='court-appeals-to' and (e.data->>'from_court_id'=qc.native_id or e.data->>'to_court_id'=qc.native_id))))
 group by s.entity_type,s.dataset,s.label,s.category,s.columns
)
insert into public.corpus_datasets(id,label,ready,expected_records,imported_records,metadata,updated_at)
select dataset,label,false,n,0,jsonb_build_object(
 'schema_version','courtlistener-reference-view/1','entity_type',entity_type,
 'source_system','courtlistener','source_as_of','2026-09-30','aliases',jsonb_build_array(dataset),
 'qualification','Official CourtListener bulk metadata snapshot dated September 30, 2026. Raw native fields, source hashes and retrieval dates are retained. Different collections describe people, aliases, positions, education or courts; their record counts must not be added as a unique-judge or current-court census. Source URLs and dates are recorded metadata, not a finding of current legal applicability.',
 'listing',jsonb_build_object('columns',jsonb_build_array(jsonb_build_object('key','name','label',case when entity_type='people' then 'Person / alias' else 'Record' end))||columns,'filters','[]'::jsonb))
 ,now() from totals
on conflict(id) do update set label=excluded.label,ready=false,imported_records=0,expected_records=excluded.expected_records,
 metadata=excluded.metadata,updated_at=excluded.updated_at;
