/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DataExportsRouteImport } from './routes/data-exports'
import { Route as EndpointExplorerRouteImport } from './routes/endpoint-explorer'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as JurisdictionsRouteImport } from './routes/jurisdictions'
import { Route as LawsRouteImport } from './routes/laws'
import { Route as MdlsRouteImport } from './routes/mdls'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as SavedSourcesRouteImport } from './routes/saved-sources'
import { Route as SourceFamiliesRouteImport } from './routes/source-families'
import { Route as PlacesIndexRouteImport } from './routes/places.index'
import { Route as PlacesStateRouteImport } from './routes/places.$state'
import { Route as PlacesStateCountyRouteImport } from './routes/places.$state.$county'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DataExportsRoute = DataExportsRouteImport.update({
  id: '/data-exports',
  path: '/data-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointExplorerRoute = EndpointExplorerRouteImport.update({
  id: '/endpoint-explorer',
  path: '/endpoint-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const JurisdictionsRoute = JurisdictionsRouteImport.update({
  id: '/jurisdictions',
  path: '/jurisdictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsRoute = LawsRouteImport.update({
  id: '/laws',
  path: '/laws',
  getParentRoute: () => rootRouteImport,
} as any)
const MdlsRoute = MdlsRouteImport.update({
  id: '/mdls',
  path: '/mdls',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSourcesRoute = SavedSourcesRouteImport.update({
  id: '/saved-sources',
  path: '/saved-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceFamiliesRoute = SourceFamiliesRouteImport.update({
  id: '/source-families',
  path: '/source-families',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesStateRoute = PlacesStateRouteImport.update({
  id: '/places/$state',
  path: '/places/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesStateCountyRoute = PlacesStateCountyRouteImport.update({
  id: '/$county',
  path: '/$county',
  getParentRoute: () => PlacesStateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/data-exports': typeof DataExportsRoute
  '/endpoint-explorer': typeof EndpointExplorerRoute
  '/insights': typeof InsightsRoute
  '/judges': typeof JudgesRoute
  '/jurisdictions': typeof JurisdictionsRoute
  '/laws': typeof LawsRoute
  '/mdls': typeof MdlsRoute
  '/overview': typeof OverviewRoute
  '/review-queue': typeof ReviewQueueRoute
  '/saved-sources': typeof SavedSourcesRoute
  '/source-families': typeof SourceFamiliesRoute
  '/places/$state': typeof PlacesStateRouteWithChildren
  '/places/': typeof PlacesIndexRoute
  '/places/$state/$county': typeof PlacesStateCountyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/data-exports': typeof DataExportsRoute
  '/endpoint-explorer': typeof EndpointExplorerRoute
  '/insights': typeof InsightsRoute
  '/judges': typeof JudgesRoute
  '/jurisdictions': typeof JurisdictionsRoute
  '/laws': typeof LawsRoute
  '/mdls': typeof MdlsRoute
  '/overview': typeof OverviewRoute
  '/review-queue': typeof ReviewQueueRoute
  '/saved-sources': typeof SavedSourcesRoute
  '/source-families': typeof SourceFamiliesRoute
  '/places/$state': typeof PlacesStateRouteWithChildren
  '/places': typeof PlacesIndexRoute
  '/places/$state/$county': typeof PlacesStateCountyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/data-exports': typeof DataExportsRoute
  '/endpoint-explorer': typeof EndpointExplorerRoute
  '/insights': typeof InsightsRoute
  '/judges': typeof JudgesRoute
  '/jurisdictions': typeof JurisdictionsRoute
  '/laws': typeof LawsRoute
  '/mdls': typeof MdlsRoute
  '/overview': typeof OverviewRoute
  '/review-queue': typeof ReviewQueueRoute
  '/saved-sources': typeof SavedSourcesRoute
  '/source-families': typeof SourceFamiliesRoute
  '/places/$state': typeof PlacesStateRouteWithChildren
  '/places/': typeof PlacesIndexRoute
  '/places/$state/$county': typeof PlacesStateCountyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/data-exports'
    | '/endpoint-explorer'
    | '/insights'
    | '/judges'
    | '/jurisdictions'
    | '/laws'
    | '/mdls'
    | '/overview'
    | '/review-queue'
    | '/saved-sources'
    | '/source-families'
    | '/places/$state'
    | '/places/'
    | '/places/$state/$county'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/data-exports'
    | '/endpoint-explorer'
    | '/insights'
    | '/judges'
    | '/jurisdictions'
    | '/laws'
    | '/mdls'
    | '/overview'
    | '/review-queue'
    | '/saved-sources'
    | '/source-families'
    | '/places/$state'
    | '/places'
    | '/places/$state/$county'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/data-exports'
    | '/endpoint-explorer'
    | '/insights'
    | '/judges'
    | '/jurisdictions'
    | '/laws'
    | '/mdls'
    | '/overview'
    | '/review-queue'
    | '/saved-sources'
    | '/source-families'
    | '/places/$state'
    | '/places/'
    | '/places/$state/$county'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  DataExportsRoute: typeof DataExportsRoute
  EndpointExplorerRoute: typeof EndpointExplorerRoute
  InsightsRoute: typeof InsightsRoute
  JudgesRoute: typeof JudgesRoute
  JurisdictionsRoute: typeof JurisdictionsRoute
  LawsRoute: typeof LawsRoute
  MdlsRoute: typeof MdlsRoute
  OverviewRoute: typeof OverviewRoute
  ReviewQueueRoute: typeof ReviewQueueRoute
  SavedSourcesRoute: typeof SavedSourcesRoute
  SourceFamiliesRoute: typeof SourceFamiliesRoute
  PlacesStateRoute: typeof PlacesStateRouteWithChildren
  PlacesIndexRoute: typeof PlacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-exports': {
      id: '/data-exports'
      path: '/data-exports'
      fullPath: '/data-exports'
      preLoaderRoute: typeof DataExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoint-explorer': {
      id: '/endpoint-explorer'
      path: '/endpoint-explorer'
      fullPath: '/endpoint-explorer'
      preLoaderRoute: typeof EndpointExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurisdictions': {
      id: '/jurisdictions'
      path: '/jurisdictions'
      fullPath: '/jurisdictions'
      preLoaderRoute: typeof JurisdictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws': {
      id: '/laws'
      path: '/laws'
      fullPath: '/laws'
      preLoaderRoute: typeof LawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdls': {
      id: '/mdls'
      path: '/mdls'
      fullPath: '/mdls'
      preLoaderRoute: typeof MdlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-sources': {
      id: '/saved-sources'
      path: '/saved-sources'
      fullPath: '/saved-sources'
      preLoaderRoute: typeof SavedSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-families': {
      id: '/source-families'
      path: '/source-families'
      fullPath: '/source-families'
      preLoaderRoute: typeof SourceFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$state': {
      id: '/places/$state'
      path: '/places/$state'
      fullPath: '/places/$state'
      preLoaderRoute: typeof PlacesStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$state/$county': {
      id: '/places/$state/$county'
      path: '/$county'
      fullPath: '/places/$state/$county'
      preLoaderRoute: typeof PlacesStateCountyRouteImport
      parentRoute: typeof PlacesStateRoute
    }
  }
}

interface PlacesStateRouteChildren {
  PlacesStateCountyRoute: typeof PlacesStateCountyRoute
}

const PlacesStateRouteChildren: PlacesStateRouteChildren = {
  PlacesStateCountyRoute: PlacesStateCountyRoute,
}

const PlacesStateRouteWithChildren = PlacesStateRoute._addFileChildren(
  PlacesStateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  DataExportsRoute: DataExportsRoute,
  EndpointExplorerRoute: EndpointExplorerRoute,
  InsightsRoute: InsightsRoute,
  JudgesRoute: JudgesRoute,
  JurisdictionsRoute: JurisdictionsRoute,
  LawsRoute: LawsRoute,
  MdlsRoute: MdlsRoute,
  OverviewRoute: OverviewRoute,
  ReviewQueueRoute: ReviewQueueRoute,
  SavedSourcesRoute: SavedSourcesRoute,
  SourceFamiliesRoute: SourceFamiliesRoute,
  PlacesStateRoute: PlacesStateRouteWithChildren,
  PlacesIndexRoute: PlacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
