/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DataExportsRouteImport } from './routes/data-exports'
import { Route as EndpointExplorerRouteImport } from './routes/endpoint-explorer'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as JurisdictionsRouteImport } from './routes/jurisdictions'
import { Route as LawRouteImport } from './routes/law'
import { Route as LawsRouteImport } from './routes/laws'
import { Route as MdlsRouteImport } from './routes/mdls'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SavedSourcesRouteImport } from './routes/saved-sources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SourceDatasetsRouteImport } from './routes/source-datasets'
import { Route as SourceFamiliesRouteImport } from './routes/source-families'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as CourtsIndexRouteImport } from './routes/courts.index'
import { Route as CourtsIdRouteImport } from './routes/courts.$id'
import { Route as DataIndexRouteImport } from './routes/data.index'
import { Route as DataDatasetRouteImport } from './routes/data.$dataset'
import { Route as JudgesIndexRouteImport } from './routes/judges.index'
import { Route as JudgesIdRouteImport } from './routes/judges.$id'
import { Route as MattersIndexRouteImport } from './routes/matters.index'
import { Route as MattersIdRouteImport } from './routes/matters.$id'
import { Route as PlacesIndexRouteImport } from './routes/places.index'
import { Route as PlacesStateRouteImport } from './routes/places.$state'
import { Route as SourcesCoverageRouteImport } from './routes/sources.coverage'
import { Route as SourcesRegistryRouteImport } from './routes/sources.registry'
import { Route as DataTablesTableRouteImport } from './routes/data.tables.$table'
import { Route as PlacesStateCountyRouteImport } from './routes/places.$state.$county'
import { Route as RecordsDatasetIdRouteImport } from './routes/records.$dataset.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DataExportsRoute = DataExportsRouteImport.update({
  id: '/data-exports',
  path: '/data-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointExplorerRoute = EndpointExplorerRouteImport.update({
  id: '/endpoint-explorer',
  path: '/endpoint-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const JurisdictionsRoute = JurisdictionsRouteImport.update({
  id: '/jurisdictions',
  path: '/jurisdictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LawRoute = LawRouteImport.update({
  id: '/law',
  path: '/law',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsRoute = LawsRouteImport.update({
  id: '/laws',
  path: '/laws',
  getParentRoute: () => rootRouteImport,
} as any)
const MdlsRoute = MdlsRouteImport.update({
  id: '/mdls',
  path: '/mdls',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSourcesRoute = SavedSourcesRouteImport.update({
  id: '/saved-sources',
  path: '/saved-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceDatasetsRoute = SourceDatasetsRouteImport.update({
  id: '/source-datasets',
  path: '/source-datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceFamiliesRoute = SourceFamiliesRouteImport.update({
  id: '/source-families',
  path: '/source-families',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsIndexRoute = CourtsIndexRouteImport.update({
  id: '/courts/',
  path: '/courts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsIdRoute = CourtsIdRouteImport.update({
  id: '/courts/$id',
  path: '/courts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDatasetRoute = DataDatasetRouteImport.update({
  id: '/data/$dataset',
  path: '/data/$dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesIndexRoute = JudgesIndexRouteImport.update({
  id: '/judges/',
  path: '/judges/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesIdRoute = JudgesIdRouteImport.update({
  id: '/judges/$id',
  path: '/judges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersIndexRoute = MattersIndexRouteImport.update({
  id: '/matters/',
  path: '/matters/',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersIdRoute = MattersIdRouteImport.update({
  id: '/matters/$id',
  path: '/matters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesStateRoute = PlacesStateRouteImport.update({
  id: '/places/$state',
  path: '/places/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesCoverageRoute = SourcesCoverageRouteImport.update({
  id: '/sources/coverage',
  path: '/sources/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRegistryRoute = SourcesRegistryRouteImport.update({
  id: '/sources/registry',
  path: '/sources/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTablesTableRoute = DataTablesTableRouteImport.update({
  id: '/data/tables/$table',
  path: '/data/tables/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesStateCountyRoute = PlacesStateCountyRouteImport.update({
  id: '/$county',
  path: '/$county',
  getParentRoute: () => PlacesStateRoute,
} as any)
const RecordsDatasetIdRoute = RecordsDatasetIdRouteImport.update({
  id: '/records/$dataset/$id',
  path: '/records/$dataset/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/data-exports': typeof DataExportsRoute
  '/endpoint-explorer': typeof EndpointExplorerRoute
  '/insights': typeof InsightsRoute
  '/jurisdictions': typeof JurisdictionsRoute
  '/law': typeof LawRoute
  '/laws': typeof LawsRoute
  '/mdls': typeof MdlsRoute
  '/overview': typeof OverviewRoute
  '/people': typeof PeopleRoute
  '/review-queue': typeof ReviewQueueRoute
  '/safety': typeof SafetyRoute
  '/saved-sources': typeof SavedSourcesRoute
  '/search': typeof SearchRoute
  '/source-datasets': typeof SourceDatasetsRoute
  '/source-families': typeof SourceFamiliesRoute
  '/api/files': typeof ApiFilesRoute
  '/courts/$id': typeof CourtsIdRoute
  '/data/$dataset': typeof DataDatasetRoute
  '/judges/$id': typeof JudgesIdRoute
  '/matters/$id': typeof MattersIdRoute
  '/places/$state': typeof PlacesStateRouteWithChildren
  '/sources/coverage': typeof SourcesCoverageRoute
  '/sources/registry': typeof SourcesRegistryRoute
  '/courts/': typeof CourtsIndexRoute
  '/data/': typeof DataIndexRoute
  '/judges/': typeof JudgesIndexRoute
  '/matters/': typeof MattersIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/data/tables/$table': typeof DataTablesTableRoute
  '/places/$state/$county': typeof PlacesStateCountyRoute
  '/records/$dataset/$id': typeof RecordsDatasetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/data-exports': typeof DataExportsRoute
  '/endpoint-explorer': typeof EndpointExplorerRoute
  '/insights': typeof InsightsRoute
  '/jurisdictions': typeof JurisdictionsRoute
  '/law': typeof LawRoute
  '/laws': typeof LawsRoute
  '/mdls': typeof MdlsRoute
  '/overview': typeof OverviewRoute
  '/people': typeof PeopleRoute
  '/review-queue': typeof ReviewQueueRoute
  '/safety': typeof SafetyRoute
  '/saved-sources': typeof SavedSourcesRoute
  '/search': typeof SearchRoute
  '/source-datasets': typeof SourceDatasetsRoute
  '/source-families': typeof SourceFamiliesRoute
  '/api/files': typeof ApiFilesRoute
  '/courts/$id': typeof CourtsIdRoute
  '/data/$dataset': typeof DataDatasetRoute
  '/judges/$id': typeof JudgesIdRoute
  '/matters/$id': typeof MattersIdRoute
  '/places/$state': typeof PlacesStateRouteWithChildren
  '/sources/coverage': typeof SourcesCoverageRoute
  '/sources/registry': typeof SourcesRegistryRoute
  '/courts': typeof CourtsIndexRoute
  '/data': typeof DataIndexRoute
  '/judges': typeof JudgesIndexRoute
  '/matters': typeof MattersIndexRoute
  '/places': typeof PlacesIndexRoute
  '/data/tables/$table': typeof DataTablesTableRoute
  '/places/$state/$county': typeof PlacesStateCountyRoute
  '/records/$dataset/$id': typeof RecordsDatasetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/data-exports': typeof DataExportsRoute
  '/endpoint-explorer': typeof EndpointExplorerRoute
  '/insights': typeof InsightsRoute
  '/jurisdictions': typeof JurisdictionsRoute
  '/law': typeof LawRoute
  '/laws': typeof LawsRoute
  '/mdls': typeof MdlsRoute
  '/overview': typeof OverviewRoute
  '/people': typeof PeopleRoute
  '/review-queue': typeof ReviewQueueRoute
  '/safety': typeof SafetyRoute
  '/saved-sources': typeof SavedSourcesRoute
  '/search': typeof SearchRoute
  '/source-datasets': typeof SourceDatasetsRoute
  '/source-families': typeof SourceFamiliesRoute
  '/api/files': typeof ApiFilesRoute
  '/courts/$id': typeof CourtsIdRoute
  '/data/$dataset': typeof DataDatasetRoute
  '/judges/$id': typeof JudgesIdRoute
  '/matters/$id': typeof MattersIdRoute
  '/places/$state': typeof PlacesStateRouteWithChildren
  '/sources/coverage': typeof SourcesCoverageRoute
  '/sources/registry': typeof SourcesRegistryRoute
  '/courts/': typeof CourtsIndexRoute
  '/data/': typeof DataIndexRoute
  '/judges/': typeof JudgesIndexRoute
  '/matters/': typeof MattersIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/data/tables/$table': typeof DataTablesTableRoute
  '/places/$state/$county': typeof PlacesStateCountyRoute
  '/records/$dataset/$id': typeof RecordsDatasetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/data-exports'
    | '/endpoint-explorer'
    | '/insights'
    | '/jurisdictions'
    | '/law'
    | '/laws'
    | '/mdls'
    | '/overview'
    | '/people'
    | '/review-queue'
    | '/safety'
    | '/saved-sources'
    | '/search'
    | '/source-datasets'
    | '/source-families'
    | '/api/files'
    | '/courts/$id'
    | '/data/$dataset'
    | '/judges/$id'
    | '/matters/$id'
    | '/places/$state'
    | '/sources/coverage'
    | '/sources/registry'
    | '/courts/'
    | '/data/'
    | '/judges/'
    | '/matters/'
    | '/places/'
    | '/data/tables/$table'
    | '/places/$state/$county'
    | '/records/$dataset/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/data-exports'
    | '/endpoint-explorer'
    | '/insights'
    | '/jurisdictions'
    | '/law'
    | '/laws'
    | '/mdls'
    | '/overview'
    | '/people'
    | '/review-queue'
    | '/safety'
    | '/saved-sources'
    | '/search'
    | '/source-datasets'
    | '/source-families'
    | '/api/files'
    | '/courts/$id'
    | '/data/$dataset'
    | '/judges/$id'
    | '/matters/$id'
    | '/places/$state'
    | '/sources/coverage'
    | '/sources/registry'
    | '/courts'
    | '/data'
    | '/judges'
    | '/matters'
    | '/places'
    | '/data/tables/$table'
    | '/places/$state/$county'
    | '/records/$dataset/$id'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/data-exports'
    | '/endpoint-explorer'
    | '/insights'
    | '/jurisdictions'
    | '/law'
    | '/laws'
    | '/mdls'
    | '/overview'
    | '/people'
    | '/review-queue'
    | '/safety'
    | '/saved-sources'
    | '/search'
    | '/source-datasets'
    | '/source-families'
    | '/api/files'
    | '/courts/$id'
    | '/data/$dataset'
    | '/judges/$id'
    | '/matters/$id'
    | '/places/$state'
    | '/sources/coverage'
    | '/sources/registry'
    | '/courts/'
    | '/data/'
    | '/judges/'
    | '/matters/'
    | '/places/'
    | '/data/tables/$table'
    | '/places/$state/$county'
    | '/records/$dataset/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  DataExportsRoute: typeof DataExportsRoute
  EndpointExplorerRoute: typeof EndpointExplorerRoute
  InsightsRoute: typeof InsightsRoute
  JurisdictionsRoute: typeof JurisdictionsRoute
  LawRoute: typeof LawRoute
  LawsRoute: typeof LawsRoute
  MdlsRoute: typeof MdlsRoute
  OverviewRoute: typeof OverviewRoute
  PeopleRoute: typeof PeopleRoute
  ReviewQueueRoute: typeof ReviewQueueRoute
  SafetyRoute: typeof SafetyRoute
  SavedSourcesRoute: typeof SavedSourcesRoute
  SearchRoute: typeof SearchRoute
  SourceDatasetsRoute: typeof SourceDatasetsRoute
  SourceFamiliesRoute: typeof SourceFamiliesRoute
  ApiFilesRoute: typeof ApiFilesRoute
  CourtsIdRoute: typeof CourtsIdRoute
  DataDatasetRoute: typeof DataDatasetRoute
  JudgesIdRoute: typeof JudgesIdRoute
  MattersIdRoute: typeof MattersIdRoute
  PlacesStateRoute: typeof PlacesStateRouteWithChildren
  SourcesCoverageRoute: typeof SourcesCoverageRoute
  SourcesRegistryRoute: typeof SourcesRegistryRoute
  CourtsIndexRoute: typeof CourtsIndexRoute
  DataIndexRoute: typeof DataIndexRoute
  JudgesIndexRoute: typeof JudgesIndexRoute
  MattersIndexRoute: typeof MattersIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
  DataTablesTableRoute: typeof DataTablesTableRoute
  RecordsDatasetIdRoute: typeof RecordsDatasetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-exports': {
      id: '/data-exports'
      path: '/data-exports'
      fullPath: '/data-exports'
      preLoaderRoute: typeof DataExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoint-explorer': {
      id: '/endpoint-explorer'
      path: '/endpoint-explorer'
      fullPath: '/endpoint-explorer'
      preLoaderRoute: typeof EndpointExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurisdictions': {
      id: '/jurisdictions'
      path: '/jurisdictions'
      fullPath: '/jurisdictions'
      preLoaderRoute: typeof JurisdictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law': {
      id: '/law'
      path: '/law'
      fullPath: '/law'
      preLoaderRoute: typeof LawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws': {
      id: '/laws'
      path: '/laws'
      fullPath: '/laws'
      preLoaderRoute: typeof LawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdls': {
      id: '/mdls'
      path: '/mdls'
      fullPath: '/mdls'
      preLoaderRoute: typeof MdlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-sources': {
      id: '/saved-sources'
      path: '/saved-sources'
      fullPath: '/saved-sources'
      preLoaderRoute: typeof SavedSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-datasets': {
      id: '/source-datasets'
      path: '/source-datasets'
      fullPath: '/source-datasets'
      preLoaderRoute: typeof SourceDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-families': {
      id: '/source-families'
      path: '/source-families'
      fullPath: '/source-families'
      preLoaderRoute: typeof SourceFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/': {
      id: '/courts/'
      path: '/courts'
      fullPath: '/courts/'
      preLoaderRoute: typeof CourtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$id': {
      id: '/courts/$id'
      path: '/courts/$id'
      fullPath: '/courts/$id'
      preLoaderRoute: typeof CourtsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$dataset': {
      id: '/data/$dataset'
      path: '/data/$dataset'
      fullPath: '/data/$dataset'
      preLoaderRoute: typeof DataDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/': {
      id: '/judges/'
      path: '/judges'
      fullPath: '/judges/'
      preLoaderRoute: typeof JudgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/$id': {
      id: '/judges/$id'
      path: '/judges/$id'
      fullPath: '/judges/$id'
      preLoaderRoute: typeof JudgesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/': {
      id: '/matters/'
      path: '/matters'
      fullPath: '/matters/'
      preLoaderRoute: typeof MattersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/$id': {
      id: '/matters/$id'
      path: '/matters/$id'
      fullPath: '/matters/$id'
      preLoaderRoute: typeof MattersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$state': {
      id: '/places/$state'
      path: '/places/$state'
      fullPath: '/places/$state'
      preLoaderRoute: typeof PlacesStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/coverage': {
      id: '/sources/coverage'
      path: '/sources/coverage'
      fullPath: '/sources/coverage'
      preLoaderRoute: typeof SourcesCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/registry': {
      id: '/sources/registry'
      path: '/sources/registry'
      fullPath: '/sources/registry'
      preLoaderRoute: typeof SourcesRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/tables/$table': {
      id: '/data/tables/$table'
      path: '/data/tables/$table'
      fullPath: '/data/tables/$table'
      preLoaderRoute: typeof DataTablesTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$state/$county': {
      id: '/places/$state/$county'
      path: '/$county'
      fullPath: '/places/$state/$county'
      preLoaderRoute: typeof PlacesStateCountyRouteImport
      parentRoute: typeof PlacesStateRoute
    }
    '/records/$dataset/$id': {
      id: '/records/$dataset/$id'
      path: '/records/$dataset/$id'
      fullPath: '/records/$dataset/$id'
      preLoaderRoute: typeof RecordsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlacesStateRouteChildren {
  PlacesStateCountyRoute: typeof PlacesStateCountyRoute
}

const PlacesStateRouteChildren: PlacesStateRouteChildren = {
  PlacesStateCountyRoute: PlacesStateCountyRoute,
}

const PlacesStateRouteWithChildren = PlacesStateRoute._addFileChildren(
  PlacesStateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  DataExportsRoute: DataExportsRoute,
  EndpointExplorerRoute: EndpointExplorerRoute,
  InsightsRoute: InsightsRoute,
  JurisdictionsRoute: JurisdictionsRoute,
  LawRoute: LawRoute,
  LawsRoute: LawsRoute,
  MdlsRoute: MdlsRoute,
  OverviewRoute: OverviewRoute,
  PeopleRoute: PeopleRoute,
  ReviewQueueRoute: ReviewQueueRoute,
  SafetyRoute: SafetyRoute,
  SavedSourcesRoute: SavedSourcesRoute,
  SearchRoute: SearchRoute,
  SourceDatasetsRoute: SourceDatasetsRoute,
  SourceFamiliesRoute: SourceFamiliesRoute,
  ApiFilesRoute: ApiFilesRoute,
  CourtsIdRoute: CourtsIdRoute,
  DataDatasetRoute: DataDatasetRoute,
  JudgesIdRoute: JudgesIdRoute,
  MattersIdRoute: MattersIdRoute,
  PlacesStateRoute: PlacesStateRouteWithChildren,
  SourcesCoverageRoute: SourcesCoverageRoute,
  SourcesRegistryRoute: SourcesRegistryRoute,
  CourtsIndexRoute: CourtsIndexRoute,
  DataIndexRoute: DataIndexRoute,
  JudgesIndexRoute: JudgesIndexRoute,
  MattersIndexRoute: MattersIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
  DataTablesTableRoute: DataTablesTableRoute,
  RecordsDatasetIdRoute: RecordsDatasetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
